#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

# NOTE(Ryan): arch-vendor-os-abi AVOE
essential="gcc-arm-none-eabi binutils-arm-none-eabi gdb-arm-none-eabi" 

testing="qemu-system-arm"

sudo apt install $essential
