#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

# listing: $(qemu-system-arm -machine help)
# qemu-system-arm -M sdsad -nographic -kernel ./build/src/emt

# IMPORTANT(Ryan): For threading, CMOCKA_TEST_ABORT='1' ./build/emt
./build/emt
